apiVersion: apps/v1
kind: Deployment
metadata: 
 name: new-deployment
spec:
 replicas: 2
 selector: 
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
   - name: mysql-container
     image: mysql
     env:
      - name: MYSQL_ROOT_PASSWORD
     volumeMounts:
     - name: secret-volume
       mountPath: "/etc/basic-auth-secret"
       readOnly: true      
     port:
     - containerPort: 3306
   volumes:
   - name: secret-volume
     secret:
      secretName: basic-auth-secret