apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
   - name: nginx-container
     image: nginx:latest
     env:
     - name: DB-PORT
       valueFrom:
        configMapKeyRef:
         name: first-cm
         key: DB-PORT
     ports:
     - containerPort: 80
