apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment-new
spec: 
 replicas: 2
 selector:
  matchLabels:
   app: new-nginx
 template:
  metadata:
   labels:
    app: new-nginx
  spec:
   containers:
   - name: nginx-new-container
     image: nginx:1.14
     volumeMounts:
     - name: volume1
       mountPath: "/etc/cm"
       readOnly: true
     ports:
     - containerPort: 80
   volumes:
   - name: volume1
     configMap: 
      name: first-cm